isic/ingest/urls.py
from django.urls import path

from isic.ingest.views.accession import accession_cog_viewer
import isic.ingest.views.cohort as cohort_views
import isic.ingest.views.metadata as metadata_views
import isic.ingest.views.review as review_views
import isic.ingest.views.upload as upload_views

urlpatterns = [
    path(
        "upload/select-or-create-contributor/",
        upload_views.select_or_create_contributor,
        name="upload/select-or-create-contributor",
    ),
    path(
        "upload/create-contributor/",
        upload_views.upload_contributor_create,
        name="upload/create-contributor",
    ),
    path(
        "upload/select-or-create-cohort/<int:contributor_pk>/",
        upload_views.select_or_create_cohort,
        name="upload/select-or-create-cohort",
    ),
    path(
        "upload/create-cohort/<int:contributor_pk>/",
        upload_views.upload_cohort_create,
        name="upload/create-cohort",
    ),
    path(
        "upload/edit-cohort/<int:cohort_pk>/",
        upload_views.upload_cohort_edit,
        name="upload/edit-cohort",
    ),
    path("upload/<int:pk>/files/", upload_views.cohort_files, name="upload/cohort-files"),
    path(
        "upload/<int:cohort_pk>/upload-single-accession/",
        upload_views.upload_single_accession,
        name="upload/single-accession",
    ),
    path("upload/<int:cohort_pk>/upload-zip/", upload_views.upload_zip, name="upload/zip"),
    path(
        "upload/<int:cohort_pk>/upload-metadata/",
        metadata_views.metadata_file_create,
        name="upload-metadata",
    ),
    path("upload/<int:pk>/publish/", cohort_views.publish_cohort, name="upload/cohort-publish"),
    # Staff pages
    path("staff/accession-cog-viewer/<int:pk>/", accession_cog_viewer, name="accession-cog-viewer"),
    path("staff/cohorts/", cohort_views.cohort_list, name="cohort-list"),
    path("staff/merge-cohorts/", cohort_views.merge_cohorts, name="merge-cohorts"),
    path("staff/ingest-review/", review_views.ingest_review, name="ingest-review"),
    path("staff/ingest-review/<int:pk>/", cohort_views.cohort_detail, name="cohort-detail"),
    path(
        "staff/ingest-review/<int:pk>/derived-collections/",
        cohort_views.cohort_derived_collections,
        name="cohort-derived-collections",
    ),
    path(
        "staff/ingest-review/<int:cohort_pk>/gallery/",
        review_views.cohort_review,
        name="cohort-review",
    ),
    path(
        "staff/ingest-review/<int:cohort_pk>/validate-metadata/",
        metadata_views.apply_metadata,
        name="validate-metadata",
    ),
    path(
        "staff/ingest-review/metadata-file/<int:metadata_file_pk>/",
        metadata_views.metadata_file_detail,
        name="metadata-file-detail",
    ),
]

isic/urls.py
from functools import partial

from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.core.exceptions import ValidationError
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from ninja import NinjaAPI
from ninja.openapi.views import openapi_view

from isic.auth import allow_any
from isic.core.api.collection import router as collection_router
from isic.core.api.doi import router as doi_router
from isic.core.api.image import ImageSearchParseError
from isic.core.api.image import router as image_router
from isic.core.api.user import router as user_router
from isic.core.sitemaps import sitemaps
from isic.find.api import autocomplete_router
from isic.find.api import router as quickfind_router
from isic.ingest.api import (
    accession_router,
    cohort_router,
    contributor_router,
    lesion_router,
    metadata_file_router,
)
from isic.stats.api import stats_router
from isic.studies.api import annotation_router, study_router, study_task_router
from isic.zip_download.api import zip_router

api = NinjaAPI(
    title="ISIC Archive",
    version="v2",
    docs_url=None,  # we want to serve the docs next to the ninja root rather than under it
    auth=allow_any,
    csrf=True,
    urls_namespace="api",
)
swagger_view = partial(openapi_view, api=api)

api.add_router("/accessions/", accession_router, tags=["accessions"])
api.add_router("/annotations/", annotation_router, tags=["annotations"])
api.add_router("/autocomplete/", autocomplete_router, tags=["autocomplete"])
api.add_router("/cohorts/", cohort_router, tags=["cohorts"])
api.add_router("/collections/", collection_router, tags=["collections"])
api.add_router("/contributors/", contributor_router, tags=["contributors"])
api.add_router("/doi/", doi_router, tags=["doi"])
api.add_router("/images/", image_router, tags=["images"])
api.add_router("/lesions/", lesion_router, tags=["lesions"])
api.add_router("/metadata-files/", metadata_file_router, tags=["metadata-files"])
api.add_router("/quickfind/", quickfind_router, tags=["quickfind"])
api.add_router("/stats/", stats_router, tags=["stats"])
api.add_router("/studies/", study_router, tags=["studies"])
api.add_router("/study-tasks/", study_task_router, tags=["study-tasks"])
api.add_router("/users/", user_router, tags=["users"])
api.add_router("/zip-download/", zip_router, tags=["zip-downloads"])


@api.exception_handler(ValidationError)
def handle_django_validation_error(request, exc: ValidationError):
    return api.create_response(
        request,
        {"message": exc.message},
        status=400,
    )


@api.exception_handler(ImageSearchParseError)
def handle_image_search_parse_error(request, exc: ImageSearchParseError):
    return api.create_response(
        request,
        {"message": "Could not parse search query."},
        status=400,
    )


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("oauth/", include("allauth.idp.urls")),
    path("admin/", admin.site.urls),
    path("api/v2/s3-upload/", include("s3_file_field.urls")),
    path("api/v2/", api.urls),
    path("api/docs/swagger/", swagger_view, name="docs-swagger"),
    path(
        "sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"
    ),
    # Core app
    path("", RedirectView.as_view(url=reverse_lazy("core/image-browser")), name="index"),
    path("", include("isic.core.urls")),
    path("", include("isic.ingest.urls")),
    path("", include("isic.stats.urls")),
    path("", include("isic.studies.urls")),
]


if settings.DEBUG:
    import debug_toolbar.toolbar

    urlpatterns += [
        *debug_toolbar.toolbar.debug_toolbar_urls(),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

isic/ingest/models/accession_review.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from .accession import Accession


class AccessionReview(models.Model):
    accession = models.OneToOneField(Accession, on_delete=models.CASCADE, related_name="review")

    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    reviewed_at = models.DateTimeField(default=timezone.now)
    value = models.BooleanField()

    class Meta:
        ordering = ["-reviewed_at"]
        get_latest_by = "reviewed_at"

    def __str__(self):
        return f"{self.creator} at {self.reviewed_at}"

isic/ingest/models/cohort.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, UniqueConstraint
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils.safestring import mark_safe

# TODO: way to view failed/skipped  accessions
from isic.core.models import CopyrightLicense, CreationSortedTimeStampedModel

from .contributor import Contributor


class Cohort(CreationSortedTimeStampedModel):
    """
    A Cohort is a container for Accessions belonging to a particular Contributor.

    A Cohort acts as a firewall for accessions, preventing specific information (like the
    Contributor) from ever being revealed. The act of publishing a Cohort creates top level Image
    objects which can be visible beyond uploaders.

    A Cohort is necessary for namespacing Accessions due to the metadata upload process
    which depends on a unique name for each Accession (see Accession.original_blob_name).

    Cohorts can point to a "magic" Collection which is used to keep track of the Accessions
    after they've been published. This is particularly useful for Cohorts that are long lived
    and receive regular data uploads.

    Cohorts can be merged together, which will transfer all of the Accessions, ZipUploads, and
    MetadataFiles. It will also merge magic Collections if possible.
    """

    class Meta(CreationSortedTimeStampedModel.Meta):
        constraints = [
            UniqueConstraint(
                name="cohort_unique_girder_id", fields=["girder_id"], condition=~Q(girder_id="")
            )
        ]

    contributor = models.ForeignKey(Contributor, on_delete=models.PROTECT, related_name="cohorts")
    creator = models.ForeignKey(User, on_delete=models.PROTECT)
    girder_id = models.CharField(blank=True, max_length=24, help_text="The dataset_id from Girder.")

    name = models.CharField(
        max_length=255,
        help_text=mark_safe(  # noqa: S308
            "The name of your Cohort. "
            "<strong>This is private</strong>, and will "
            "not be published along with your images."
        ),
    )
    description = models.TextField(
        help_text=mark_safe(  # noqa: S308
            "The description of your Cohort."
            "<strong>This is private</strong>, and will not be published along "
            "with your images.<br />"
            'Supports <a href="https://www.markdownguide.org/cheat-sheet/">markdown</a>.'
        )
    )

    # This is the default copyright_license accessions will be assigned, but accessions can have
    # different licenses within the same cohort.
    default_copyright_license = models.CharField(choices=CopyrightLicense.choices, max_length=255)

    # required if default_copyright_license is CC-BY-*
    default_attribution = models.CharField(
        help_text="The institution name that should be attributed.", max_length=200
    )

    collection = models.OneToOneField(
        "core.Collection", null=True, on_delete=models.SET_NULL, related_name="cohort"
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("cohort-detail", args=[self.id])

    @property
    def num_lesions(self):
        return self.accessions.exclude(lesion=None).values("lesion__id").distinct().count()

    @property
    def num_patients(self):
        return self.accessions.exclude(patient=None).values("patient__id").distinct().count()


class CohortPermissions:
    model = Cohort
    perms = ["view_cohort", "add_accession", "edit_cohort"]
    filters = {"view_cohort": "view_cohort_list", "edit_cohort": "edit_cohort_list"}

    @staticmethod
    def view_cohort_list(user_obj: User, qs: QuerySet[Cohort] | None = None) -> QuerySet[Cohort]:
        qs = qs if qs is not None else Cohort._default_manager.all()

        if user_obj.is_staff:
            return qs
        if user_obj.is_authenticated:
            return qs.filter(contributor__owners__in=[user_obj])

        return qs.none()

    @staticmethod
    def edit_cohort_list(user_obj: User, qs: QuerySet[Cohort] | None = None) -> QuerySet[Cohort]:
        qs = qs if qs is not None else Cohort._default_manager.all()

        if user_obj.is_staff:
            return qs
        if user_obj.is_authenticated:
            return qs.filter(contributor__owners__in=[user_obj])

        return qs.none()

    @staticmethod
    def view_cohort(user_obj, obj):
        return CohortPermissions.view_cohort_list(user_obj).contains(obj)

    @staticmethod
    def edit_cohort(user_obj, obj):
        return CohortPermissions.edit_cohort_list(user_obj).contains(obj)

    @staticmethod
    def add_accession(user_obj: User, obj: Cohort) -> bool:
        return obj and user_obj.is_authenticated and obj.contributor.owners.contains(user_obj)


Cohort.perms_class = CohortPermissions

isic/ingest/models/unstructured_metadata.py
from django.db import models

from isic.ingest.models.accession import Accession


class UnstructuredMetadata(models.Model):
    accession = models.OneToOneField(
        Accession, on_delete=models.CASCADE, related_name="unstructured_metadata"
    )
    value = models.JSONField(default=dict, blank=True)

    def __str__(self) -> str:
        return f"{self.pk}"

isic/ingest/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import ModelForm
from isic_metadata import FIELD_REGISTRY
from isic_metadata.fields import (
    AnatomSiteGeneralEnum,
    DermoscopicTypeEnum,
    DiagnosisConfirmTypeEnum,
    ImageTypeEnum,
)
from s3_file_field.forms import S3FormFileField

from isic.core.models.collection import Collection
from isic.ingest.models import Cohort, Contributor


def choice_field_from_enum(field_name: str, enum) -> forms.ChoiceField:
    label = None

    if hasattr(FIELD_REGISTRY[field_name], "label"):
        label = FIELD_REGISTRY[field_name].label

    # sort choices by their 'label' even though we don't have labels yet
    choices = sorted(((i.value, i.value) for i in enum), key=lambda x: x[1])

    return forms.ChoiceField(choices=choices, required=False, label=label)


class CohortForm(ModelForm):
    class Meta:
        model = Cohort
        fields = ["name", "description", "default_copyright_license", "default_attribution"]

    def save(self, commit=True):  # noqa: FBT002
        instance = super().save(commit=False)

        # if the cohort name changed, update the magic collection name
        if instance.pk and instance.collection and "name" in self.changed_data:
            instance.collection.name = f"Publish of {instance.name}"
            if commit:
                instance.collection.save(update_fields=["name"])

        if commit:
            instance.save()

        return instance


class ContributorForm(ModelForm):
    class Meta:
        model = Contributor
        fields = [
            "institution_name",
            "legal_contact_info",
            "default_copyright_license",
            "default_attribution",
        ]

    institution_url = forms.URLField(assume_scheme="http")


class SingleAccessionUploadForm(forms.Form):
    original_blob = S3FormFileField(model_field_id="ingest.Accession.original_blob", label="Image")

    age = forms.IntegerField(min_value=1, max_value=85, required=False)
    sex = forms.ChoiceField(choices=[("male", "male"), ("female", "female")], required=False)
    anatom_site_general = choice_field_from_enum("anatom_site_general", AnatomSiteGeneralEnum)
    diagnosis_confirm_type = choice_field_from_enum(
        "diagnosis_confirm_type", DiagnosisConfirmTypeEnum
    )
    image_type = choice_field_from_enum("image_type", ImageTypeEnum)
    dermoscopic_type = choice_field_from_enum("dermoscopic_type", DermoscopicTypeEnum)


class MergeCohortForm(forms.Form):
    cohort = forms.ModelChoiceField(
        widget=forms.HiddenInput(),
        queryset=Cohort.objects.all(),
        required=True,
        label="Cohort to merge into",
        help_text="The selected cohort will be the one that remains after the merge.",
    )
    cohort_to_merge = forms.ModelChoiceField(
        widget=forms.HiddenInput(),
        queryset=Cohort.objects.all(),
        required=True,
        label="Cohort to merge",
        help_text="The selected cohort will be deleted after the merge.",
    )

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data = cleaned_data if cleaned_data is not None else {}
        cohort = cleaned_data.get("cohort")
        cohort_to_merge = cleaned_data.get("cohort_to_merge")

        if cohort and cohort_to_merge and cohort == cohort_to_merge:
            raise forms.ValidationError("The two cohorts must be different.")

        return cleaned_data


class PublishCohortForm(forms.Form):
    public = forms.BooleanField(
        label="Public",
        required=False,
        help_text="Make this cohort publicly accessible.",
    )

    additional_collections = forms.ModelMultipleChoiceField(
        label="Additional collections",
        queryset=Collection.objects.all(),
        required=False,
        help_text="Additional collections to add these images to.",
    )

    def clean(self):
        cleaned_data = super().clean()
        assert cleaned_data  # noqa: S101

        # note that this logic is duplicated in cohort_publish_initialize, this is just
        # added for easier form validation.
        has_public_additional_collections = Collection.objects.filter(
            pk__in=cleaned_data.get("additional_collections", []), public=True
        ).exists()

        if not cleaned_data["public"] and has_public_additional_collections:
            raise ValidationError("Can't add private images into a public collection.")

        return cleaned_data

isic/ingest/views/accession.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, render

from isic.ingest.models.accession import Accession


@staff_member_required
def accession_cog_viewer(request, pk):
    accession = get_object_or_404(Accession, pk=pk)

    return render(
        request,
        "ingest/accession_cog_viewer.html",
        {
            "accession": accession,
        },
    )

isic/ingest/templates/ingest/partials/accession.html
{% load accession %}

<div class="col accession-col" {% if review_mode %}x-data="accession({{ accession.id }});"{% endif %}>
  <div x-data="{ open: false, hovered: false }" class="pb-4">
    <a class="cursor-pointer">
      {% if accession.is_cog %}
        <a href="{% url 'accession-cog-viewer' accession.id %}">
          <img src="{{ accession.thumbnail_.url }}" />
        </a>
      {% else %}
        <img @mouseenter="hovered = true" @click="open = true" src="{{ accession.thumbnail_.url }}" />
      {% endif %}
    </a>

    <div x-cloak x-show="open">
      {% include 'ingest/partials/accession_modal.html' %}
    </div>
  </div>
  <div class="flex justify-around">
    <span>{{ accession.get_diagnosis_display }}</span>
    {% if include_acquisition_day %}
      <span>
        {% if accession.metadata.acquisition_day %}
          (Day {{ accession.metadata.acquisition_day }})
        {% endif %}
      </span>
    {% endif %}
  </div>
  {% if review_mode %}
    <div class="flex justify-evenly">
      <button @click="toggleReject()" class="btn btn-sm btn-error review-button" :class="{'dim': review === false}">Reject</button>
    </div>
  {% endif %}
</div>

isic/ingest/templates/ingest/partials/breadcrumbs.html
<nav class="flex" aria-label="Breadcrumb">
  <ol class="flex items-center space-x-4">
    <li>
      <div>
        <a href="/" class="text-gray-400 hover:text-gray-500">
          <i class="ri-home-2-fill flex-shrink-0 text-xl" aria-hidden="true"></i>
          <span class="sr-only">Home</span>
        </a>
      </div>
    </li>

    {% for breadcrumb in breadcrumbs %}
      <li>
        <div class="flex items-center">
          <i class="ri-arrow-right-s-line flex-shrink-0 text-gray-400" aria-hidden="true"></i>
          <a href="{{ breadcrumb.0 }}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">{{ breadcrumb.1 }}</a>
        </div>
      </li>
    {% endfor %}
  </ol>
</nav>

isic/ingest/templates/ingest/partials/cohort_actions.html
<div class="relative inline-block text-left" x-data="{open: false}">
  <div>
    <button @click.away="open = false" @click="open = !open" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500" id="menu-button" aria-expanded="true" aria-haspopup="true">
      Actions
      <i class="ri-arrow-down-s-line -mr-1 ml-2 text-sm inline-block align-middle" aria-hidden="true"></i>
    </button>
  </div>
  <div x-cloak x-show="open" class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1" role="none">
      <a href="{% url 'upload/edit-cohort' cohort.pk %}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Edit Cohort</a>
    </div>
    <div class="py-1" role="none">
      {% url 'cohort-review' cohort.pk as review_url %}
      <a href="{{ review_url }}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Review Cohort</a>
      <a href="{{ review_url }}{% querystring grouped_by_lesion="1" %}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Review Cohort by Lesion</a>
    </div>
    <div class="py-1" role="none">
      <a href="{% url 'upload/cohort-files' cohort.pk %}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Add additional files</a>
      <a href="{% url 'validate-metadata' cohort.pk %}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Validate & Apply Metadata</a>
    </div>
    <div class="py-1" role="none">
      <a href="{% url 'upload/cohort-publish' cohort.pk %}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Publish Cohort</a>
    </div>
  </div>
</div>

isic/ingest/templates/ingest/partials/cohort_details.html
{% load localtime %}
{% load humanize %}
{% load markdownify %}

<div id="detail-info">
  <ul>
    <li><span class="font-bold">Name:</span> {{ cohort.name }}</li>
    <li><span class="font-bold">Description:</span> {{ cohort.description|markdownify }}</li>
    <li><span class="font-bold">Default Attribution:</span> {{ cohort.default_attribution }}</li>
    <li><span class="font-bold">Default License:</span> {{ cohort.get_default_copyright_license_display }}</li>
    <li><span class="font-bold">Created by:</span> {{ cohort.creator.first_name }} {{ cohort.creator.last_name }} ({{ cohort.creator }})</li>
    <li><span class="font-bold">Created on:</span> {% localtime cohort.created %}</li>
    {% if cohort.collection %}
      <li><span class="font-bold">Magic Collection:</span> <a href="{% url 'core/collection-detail' cohort.collection.pk %}" class="text-blue-500 hover:underline">{{ cohort.collection.name }}</a></li>
    {% endif %}
    <li><span class="font-bold">Number of accessions:</span> {{ counts.accession_count|intcomma }}</li>
    <li><span class="font-bold">Number of lesions:</span> {{ counts.lesion_count|intcomma }}</li>
    <li><span class="font-bold">Number of patients:</span> {{ counts.patient_count|intcomma }}</li>
    <li><span class="font-bold">Published:</span> {{ counts.published_count|intcomma }}</li>
    <li><span class="font-bold">Unreviewed:</span> {{ counts.unreviewed_count|intcomma }}</li>
    <li><span class="font-bold">Accepted:</span> {{ counts.accepted_count|intcomma }}</li>
    <li><span class="font-bold">Rejected:</span> {{ counts.rejected_count|intcomma }}</li>
    <li><span class="font-bold">Ignored (invalid images):</span>
      {% if counts.skipped_count > 0 %}
        <a href="{% querystring show_skipped='true' %}" class="text-blue-500 hover:underline">{{ counts.skipped_count|intcomma }}</a>
      {% else %}
        {{ counts.skipped_count|intcomma }}
      {% endif %}
    </li>
  </ul>
</div>

isic/ingest/templates/ingest/partials/cohort_list_actions.html
<div class="relative inline-block text-left" x-data="{open: false}">
  <div>
    <button @click.away="open = false" @click="open = !open" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500" id="menu-button" aria-expanded="true" aria-haspopup="true">
      Actions
      <i class="ri-arrow-down-s-line -mr-1 ml-2 text-sm inline-block align-middle" aria-hidden="true"></i>
    </button>
  </div>
  <div x-cloak x-show="open" class="z-10 origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1" role="none">
      <a href="{% url 'merge-cohorts' %}" class="hover:bg-gray-100 hover:text-gray-900 text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Merge Cohorts</a>
    </div>
  </div>
</div>

isic/ingest/templates/ingest/partials/grouped_review_footer.html
{{ checks|json_script:"checks" }}

<div x-data="submitReviewButton()">

  <button
    :disabled="submitting || submitted"
    @click="submit"
    type="button"
    class="review-button inline-flex items-center px-2.5 py-1.5 border border-transparent text-s font-medium rounded shadow-sm hover:text-white text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">

    <div x-show="submitting" class="flex">
      <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
      <span>Submitting</span>
    </div>

    <div x-show="!submitting">
      <div x-show="submitted">
        Submitted
      </div>
      <div x-show="!submitted">
        Accept remaining
      </div>
    </div>
  </button>

</div>

<script type="text/javascript">
  function submitReviewButton() {
    return {
      submitting: false,
      submitted: false,
      submit() {
        this.submitting = true;
        let submissions = [];
        let checks = JSON.parse(document.getElementById('checks').textContent);

        $('.accession-col').map(function(i, el) {
          // fetch id from alpine data
          let accessionId = el.__x.$data.id;
          submissions.push(fetch(`/api/v2/accessions/${accessionId}/soft_accept/`, {
            method: 'PATCH',
            headers: {
              'Content-Type': 'application/json',
              'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify(
              _.zipObject(checks, _.fill(_.clone(checks), true))
            ),
          }));
        });

        Promise.all(submissions).then((values) => {
          this.submitted = true;
           this.submitting = false;
        });
      }
    }
  }
</script>

isic/ingest/templates/ingest/partials/merge_cohort_preview.html
<ul x-show="results.length > 0" class="menu bg-base-200 max-w-xs p-4 rounded-box">
  <template x-for="result in results">
    <li><a class="p-2" x-text="result.name" x-on:click="select(result)"></a></li>
  </template>
</ul>

<div x-show="resultPreview">
  <div class="my-4 bg-gray-50 p-2 rounded-sm border-gray-200 border">
    <ul>
      <li><span class="font-bold">Name: </span><span x-text="resultPreview.name"></span></li>
      <li><span class="font-bold">Description: </span><span x-text="resultPreview.description"></span></li>
      <li><span class="font-bold">Default Attribution: </span><span x-text="resultPreview.default_attribution"></span></li>
      <li><span class="font-bold">Default License: </span><span x-text="resultPreview.default_copyright_license"></span></li>
      <li><span class="font-bold">Accessions: </span><span x-text="new Intl.NumberFormat('en-US').format(resultPreview.accession_count)"></span></li>
    </ul>
  </div>
</div>

<hr class="my-4" />